In [1]:
import numpy as np
import pandas as pd

In [2]:
final_data = pd.read_csv('../datasets/final_data.csv')

In [3]:
final_data.head()

director_name     actor_1_name     actor_2_name          actor_3_name  \
0     Gore Verbinski      Johnny Depp    Orlando Bloom        Jack Davenport   
1         Sam Mendes  Christoph Waltz     Rory Kinnear      Stephanie Sigman   
2  Christopher Nolan        Tom Hardy   Christian Bale  Joseph Gordon-Levitt   
3        Doug Walker      Doug Walker       Rob Walker               unknown   
4     Andrew Stanton     Daryl Sabara  Samantha Morton          Polly Walker   

                      genres  \
0   Action Adventure Fantasy   
1  Action Adventure Thriller   
2            Action Thriller   
3                Documentary   
4    Action Adventure Sci-Fi   

                                         movie_title  \
0           pirates of the caribbean: at world's end   
1                                            spectre   
2                              the dark knight rises   
3  star wars: episode vii - the force awakens    ...   
4                                        john carter   

                                                tags  
0  Action Adventure Fantasy pirates of the caribb...  
1  Action Adventure Thriller spectre Christoph Wa...  
2  Action Thriller the dark knight rises Tom Hard...  
3  Documentary star wars: episode vii - the force...  
4  Action Adventure Sci-Fi john carter Daryl Saba...

In [4]:
#CountVectorizer counts text(TAGS) converted into vectors.
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 6000, stop_words = 'english')

In [5]:
vectors = cv.fit_transform(final_data['tags']).toarray()

In [6]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [7]:
vectors.shape

(6308, 6000)

In [8]:
cv.get_feature_names()

['000',
 '10',
 '11',
 '12',
 '13',
 '13th',
 '20',
 '2000',
 '21',
 '22',
 '28',
 '30',
 '300',
 '3d',
 '40',
 '47',
 '50',
 '51',
 '55',
 '5th',
 'aaron',
 'aasif',
 'abbie',
 'abbott',
 'abby',
 'abdul',
 'abe',
 'abel',
 'abhishek',
 'abigail',
 'abraham',
 'abrams',
 'academy',
 'ace',
 'ackles',
 'act',
 'action',
 'activity',
 'adam',
 'adams',
 'adamson',
 'addams',
 'addison',
 'addy',
 'adjani',
 'adler',
 'adrian',
 'adriana',
 'adrienne',
 'adventure',
 'adventures',
 'affair',
 'affleck',
 'africa',
 'afterlife',
 'agata',
 'age',
 'agent',
 'agnes',
 'agnieszka',
 'aguilar',
 'agutter',
 'ahmed',
 'ahn',
 'aida',
 'aidan',
 'aiello',
 'aiken',
 'aimee',
 'air',
 'aisha',
 'aj',
 'aja',
 'ajay',
 'aki',
 'akil',
 'akira',
 'akiva',
 'akon',
 'aksel',
 'akshaye',
 'al',
 'alain',
 'alan',
 'alanna',
 'albert',
 'alden',
 'aldis',
 'alec',
 'alejandro',
 'aleksandr',
 'aleksey',
 'alessandro',
 'alex',
 'alexa',
 'alexander',
 'alexandra',
 'alexandre',
 'alexis',
 'alfie',


In [9]:
#Stem words
import nltk
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [10]:
def stemmer(x):
    stem_word = []
    string = " "
    
    for i in x.split():
        stem_word.append(ps.stem(i))
        
    return string.join(stem_word)

In [11]:
final_data['tags'] = final_data['tags'].map(lambda x: stemmer(x))

In [12]:
vectors = cv.fit_transform(final_data['tags']).toarray()

In [13]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [14]:
cv.get_feature_names()

['000',
 '10',
 '11',
 '12',
 '13',
 '13th',
 '15',
 '16',
 '17',
 '19',
 '1984',
 '20',
 '2000',
 '21',
 '22',
 '28',
 '30',
 '300',
 '3000',
 '33',
 '3d',
 '40',
 '47',
 '50',
 '51',
 '55',
 '5th',
 'aaliyah',
 'aarniokoski',
 'aaron',
 'aasif',
 'abandon',
 'abbi',
 'abbott',
 'abdalla',
 'abdul',
 'abe',
 'abel',
 'abhishek',
 'abid',
 'abigail',
 'abkarian',
 'abl',
 'abo',
 'abraham',
 'abrahamson',
 'abram',
 'academi',
 'ace',
 'acker',
 'ackerman',
 'ackl',
 'act',
 'action',
 'activ',
 'activity',
 'actual',
 'adam',
 'adamson',
 'adan',
 'addam',
 'addi',
 'addison',
 'adel',
 'adelaid',
 'adelman',
 'adelstein',
 'aden',
 'adina',
 'adir',
 'aditya',
 'adjani',
 'adkin',
 'adler',
 'adrian',
 'adriana',
 'adrien',
 'adrienn',
 'adsit',
 'adventur',
 'adèl',
 'afabl',
 'affair',
 'affleck',
 'afraid',
 'africa',
 'afterlif',
 'aftermath',
 'agata',
 'age',
 'agent',
 'agn',
 'agnieszka',
 'aguilar',
 'agutt',
 'ahead',
 'ahm',
 'ahmad',
 'ahn',
 'aida',
 'aidan',
 'aiello',


In [15]:
#Cosine Similarity measures similarity between two vectors.
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)

In [16]:
similarity[1]

array([0.16329932, 1.        , 0.25354628, ..., 0.        , 0.        ,
       0.        ])

In [17]:
def recommend(movie):
    movie_index = final_data[final_data['movie_title'] == movie].index[0]
    distances = similarity[movie_index]
    recommended_movies_list = sorted(list(enumerate(distances)),reverse = True,key = lambda x: x[1])[1:9]
    
    for i in recommended_movies_list:
        print(final_data.iloc[i[0]].movie_title)

In [18]:
recommend('spider-man: no way home')

spider-man: far from home
about time
the courier
iron man
iron man 2
spider-man: into the spider-verse
the fifth estate
cherry


In [19]:
import pickle

In [20]:
#Pickle file is used to transport any object to another Python IDE. 
pickle.dump(final_data.to_dict(),open('final_data_dict.pkl','wb'))
pickle.dump(similarity, open('similarity.pkl','wb'))